/**
 * AUTO-GENERATED by `npm run voiceover`. Do not edit by hand.
 * Lists the audio that actually exists so <Audio> never points at a missing file.
 */
import type { SceneKey } from "./utils/timing";

export const VO_AVAILABLE: SceneKey[] = ["logo", "problem", "platform", "pipeline", "architecture", "features", "cta"];

/** Set true once you add `public/audio/music.mp3`. */
export const HAS_MUSIC = false;

/** Music bed level — kept well under the narration. */
export const MUSIC_VOLUME = 0.16;
